name: simple_app
description: "A Simple Flutter Project"

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.8
  get_it: ^7.7.0
  shared_preferences: ^2.2.3
  google_fonts: ^6.2.0
  flex_color_scheme: ^7.3.1
  gettext: ^1.2.0
  get: ^4.6.6
  go_router: ^13.2.4
  cached_network_image: ^3.3.1
  getwidget: ^4.0.0
  calendar_view: ^1.2.0
  timelines: ^0.1.0
  fl_chart: ^0.67.0
  flutter_svg: ^2.0.10+1
  animations: ^2.0.11
  dio: ^5.4.3+1
  intl: ^0.19.0
  socket_io_client: ^1.0.2
  awesome_snackbar_content: ^0.1.3
  
  flutter_localizations:
    sdk: flutter
  dartz: ^0.10.1
  provider: ^6.1.2
  image_picker: ^1.1.2
  sqflite: ^2.4.1
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0

flutter:


  uses-material-design: true

